#!/bin/sh
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:10:00
#PBS -q hepx
#PBS -t 0-0
cd /home/aperloff/JEC/CMSSW_7_3_3_testPUPPI/src
export SCRAM_ARCH=slc6_amd64_gcc491
eval `scramv1 runtime -sh`
cd /fdata/hepx/store/user/aperloff/JEC/

#export RELEASE_ERA="72X_PHYS14"
#export RELEASE_ERA="73X_Spring15"
export RELEASE_ERA="73X_testPUPPI"

jet_combine_closure_pt_x ${RELEASE_ERA}/batchInputJetCombineClosurePt${SLURM_ARRAY_TASK_ID}.txt

exit 0